### ISSUE TITLE
clip1 description

### ISSUE THREAD

**Issue by pcroland** [Asd-g/AviSynth-MatchHistogram#1]
Hi! Could you please update the description for clip1? I understand that clip2 is the source that will be changed and clip3 is the target but what does clip1 do? Thanks in advance.

**Comment by Asd-g** [comment]
Clip1 is the source.
Clip2 is the target.
The difference between clip1 and clip2 is calculated.
That difference is applied on clip3. You can apply the difference between clip1 and clip2 on any clip with the same format and dimension as clip1.

**Comment by pcroland** [comment]
Hmmm, why would I apply the difference on a third clip? I can't think of any use case.

**Comment by Asd-g** [comment]
With version 2.1.2 clip3 is actually optional.

**Comment by pcroland** [comment]
Oh, thanks a lot.
